name: Build and Test Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --continue

    - name: Save build result to summary.md
      run: |
        echo "# Build Summary" > summary.md
        echo "## Build Result" >> summary.md
        ./gradlew build >> summary.md
        echo "Build step completed" >> summary.md
    
    - name: Archive summary.md
      uses: actions/upload-artifact@v2
      with:
        name: SummaryResult
        path: summary.md
