name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 28
          build-tools: 28.0.3
      - name: Update SDK package list 
        run: sudo apt-get update  
      - name: Install necessary packages
        run: |
          sudo apt-get install -y lib32z1 lib32ncurses6 lib32stdc++6
      
      - name: Clean Gradle cache
        run: rm -rf $HOME/.gradle/caches/
        continue-on-error: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --stacktrace --info
        continue-on-error: true

      - name: Run tests
        run: ./gradlew test --stacktrace --info
        continue-on-error: true

      - name: Generate summary
        run: |
          echo "# Summary" > summary.md
          echo "## Build" >> summary.md
          ./gradlew build --stacktrace --info >> summary.md 2>&1 || true
          echo "## Tests" >> summary.md
          ./gradlew test --stacktrace --info >> summary.md 2>&1 || true

      - name: Upload summary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: SummaryResult
          path: summary.md