name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          continue-on-error: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        continue-on-error: true

      - name: Build with Gradle
        run: ./gradlew build
        continue-on-error: true

      - name: Run tests
        run: ./gradlew test
        continue-on-error: true

      - name: Generate summary
        run: |
          echo "# Summary" > summary.md
          echo "## Build" >> summary.md
          ./gradlew build >> summary.md 2>&1 || true
          echo "## Tests" >> summary.md
          ./gradlew test >> summary.md 2>&1 || true

      - name: Upload summary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: SummaryResult
          path: summary.md