name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        continue-on-error: true

      - name: Run build
        run: npm run build
        continue-on-error: true

      - name: Run tests
        run: npm test
        continue-on-error: true

      - name: Generate summary
        run: |
          echo "# Summary" > summary.md
          echo "## Install dependencies" >> summary.md
          npm install >> summary.md 2>&1 || true
          echo "## Build" >> summary.md
          npm run build >> summary.md 2>&1 || true
          echo "## Tests" >> summary.md
          npm test >> summary.md 2>&1 || true

      - name: Upload summary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: SummaryResult
          path: summary.md